Expand CI steps

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -46,13 +46,30 @@ jobs:
     runs-on: ubuntu-latest
     needs: prepare-base
     steps:
-      - name: Restore pre-commit environment from cache
-        id: cache-precommit
+      - name: Check out code from GitHub
+        uses: actions/checkout@v2
+
+      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
+        id: python
+        uses: actions/setup-python@v4
+        with:
+          python-version: ${{ env.DEFAULT_PYTHON }}
+
+      - name: Restore base Python virtual environment
+        id: cache-venv
         uses: actions/cache@v3
         with:
           path: ${{ env.PRE_COMMIT_HOME }}
           key: |
-            pre-commit-${{ env.CACHE_VERSION }}-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
+            base-${{ env.CACHE_VERSION }}-${{ runner.os }}-${{ steps.python.outputs.python-version }}-${{ hashFiles('.pre-commit-config.yaml') }}
+
+      - name: Create Python virtual environment
+        if: steps.cache-venv.outputs.cache-hit != 'true'
+        run: |
+          python -m venv venv
+          . venv/bin/activate
+          pip install -U pip wheel setuptools pre-commit
+          pip install -e '.[testing]'
 
       - name: Install pre-commit dependencies
         if: steps.cache-precommit.outputs.cache-hit != 'true'
@@ -70,6 +87,29 @@ jobs:
     needs: prepare-base
     name: Run tests
     steps:
+      - name: Check out code from GitHub
+        uses: actions/checkout@v2
+
+      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
+        id: python
+        uses: actions/setup-python@v4
+        with:
+          python-version: ${{ env.DEFAULT_PYTHON }}
+
+      - name: Restore base Python virtual environment
+        id: cache-venv
+        uses: actions/cache@v3
+        with:
+          path: venv
+          key: |
+            base-${{ env.CACHE_VERSION }}-${{ runner.os }}-${{ steps.python.outputs.python-version }}-${{ hashFiles('setup.cfg') }}
+
+      - name: Fail job if Python cache restore failed
+        if: steps.cache-venv.outputs.cache-hit != 'true'
+        run: |
+          echo "Failed to restore Python virtual environment from cache"
+          exit 1
+
       - name: Register Python problem matcher
         run: |
           echo "::add-matcher::.github/workflows/matchers/python.json"
@@ -96,6 +136,29 @@ jobs:
     runs-on: ubuntu-latest
     needs: pytest
     steps:
+      - name: Check out code from GitHub
+        uses: actions/checkout@v2
+
+      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
+        id: python
+        uses: actions/setup-python@v4
+        with:
+          python-version: ${{ env.DEFAULT_PYTHON }}
+
+      - name: Restore base Python virtual environment
+        id: cache-venv
+        uses: actions/cache@v3
+        with:
+          path: venv
+          key: |
+            base-${{ env.CACHE_VERSION }}-${{ runner.os }}-${{ steps.python.outputs.python-version }}-${{ hashFiles('setup.cfg') }}
+
+      - name: Fail job if Python cache restore failed
+        if: steps.cache-venv.outputs.cache-hit != 'true'
+        run: |
+          echo "Failed to restore Python virtual environment from cache"
+          exit 1
+
       - name: Download all coverage artifacts
         uses: actions/download-artifact@v3
 
